_defaults:
  kongctl:
    namespace: destinations

control_planes:
  - ref: flight-data-dev
    _external:
      selector:
        matchFields:
          name: flight-data-dev
    _deck:
      files:
        - ../gateway/dev/kong.yaml
      flags:
        - --analytics=false

apis:
  - ref: destinations-dev-api
    name: KongAir Destinations - Development
    description: Development Catalog API owned by the Destinations service team.
    versions:
      - ref: destinations-dev-0-1-0
        version: !file ../openapi.yaml#info.version
        spec: !file ../openapi.yaml
    publications:
      - ref: destinations-dev-publication
        portal_id: !lookup {name: KongAirlines Development}
        visibility: private
    implementations:
      - ref: destinations-dev-control-plane
        type: control_plane
        control_plane:
          control_plane_id: !ref flight-data-dev#id
